spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: tts-service
          uri: http://localhost:14982
          predicates:
            - Path=/tts/**
          filters:
            - RemoveRequestHeader=Cookie
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://localhost:14980/auth/realms/myalomatika/protocol/openid-connect/token
            authorization-uri: http://localhost:14980/auth/realms/myalomatika/protocol/openid-connect/auth
            userinfo-uri: http://localhost:14980/auth/realms/myalomatika/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
        registration:
          myalomatika-app-scope:
            provider: keycloakdf
            client-id: myalomatika-app
            client-secret: 52bcc30c-b22f-4139-84d9-c3e567ec8993
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"

server.port: 14981

logging.level:
  org.springframework.cloud.gateway: DEBUG
  org.springframework.security: DEBUG
  org.springframework.web.reactive.function.client: TRACE